# Generated by Django 3.2.9 on 2025-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.CharField(max_length=2000),
        ),
    ]
